server:
  port: 10086
  servlet:
    session:
      timeout: 3600s

spring:
  datasource:
    username: root
    password: 160778
    url: jdbc:mysql://192.168.213.132:3306/neimeng?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapping/*Mapping.xml
  type-aliases-package: com.example.entity

log:
  path: /var/log/demo #日志路径
  level: info